= Analytics SDK Release Notes
:description: Release notes, brief installation instructions, and download archive for the Enterprise Analytics Python Client.
:navtitle: Release Notes
:page-toclevels: 2
// :page-aliases: sdk-release-notes.adoc

// tag::all[]
[abstract]
{description}

Version {sdk_dot_minor} of the Python Analytics SDK implements the {sdk_api} xref:compatibility.adoc#api-version[SDK API].
See the xref:compatibility.html#couchbase-feature-availability-matrix[compatibility pages] for more information on feature compatibility with different versions of Enterprise Analytics.


== Installation

See the xref:project-docs:sdk-full-installation.adoc[Full Installation] guide for details.

// tag::all[]


[#latest-release]
== Python Analytics SDK 1.1 Releases

We always recommend using the latest version of the SDK -- it contains all of the latest security patches and support for new and upcoming features.
All patch releases for each dot minor release should be API compatible, and safe to upgrade;
any changes to expected behavior are noted in the release notes that follow.




[[v1.1.0]]
=== Version 1.1.0 (26 June 2026)

This is the first release of the 1.1 series Analytics Python SDK.

The 1.1 Analytics SDKs add support for JWT and client certificate authentication,
as well as a new poll-based {async-server-api-feature-name} that uses request handles to fetch results,
eliminating the need for long-running server connections (compatible with Couchbase Enterprise Analytics Server 2.2).

https://docs.couchbase.com/sdk-api/analytics-python-client-1.1.0/[API Reference]







== Python Analytics SDK 1.0 Releases

[[v1.0.0]]
=== Version 1.0.0 (12 August 2025)

This is the first General Availability (GA) release of the new Analytics Python SDK.
It supports executing queries against Enterprise Analytics clusters, with additional features planned for future releases.

https://docs.couchbase.com/sdk-api/analytics-python-client-1.0.0/[API Reference]
// end::all[]
