= Compatibility
:description: Platform compatibility, and features available in different SDK versions, and compatibility between Enterprise Analytics and Analytics SDK.
:page-toclevels: 3
:table-caption!:


[abstract]
{description}
// Plus notes on Cloud, networks, and AWS Lambda.





== Platform Compatibility


=== Python Version Compatibility

Currently Python 3.9 - Python 3.13 is supported.

// TIP: Remember to keep your Python installation up to date, via `pip`.



=== OS Compatibility

include::{sdk_api}@analytics-sdk:shared:partial$compatibility.adoc[tag=os-compat]





=== Network Requirements

include::{sdk_api}@analytics-sdk:shared:partial$network-requirements.adoc[tag=lan-like]






== Enterprise Analytics Compatibility

The 1.1 releases of the Analytics SDK is fully compatible with currently supported releases of Enterprise Analytics - `1.0` and `1.1`.
The 1.1 Python SDK also supports an asynchronous (streaming) API update for a forthcoming release of self-managed Enterprise Analytics Server.


////
is a fully hosted service, continually updated, and offering the latest version --
with users having a few weeks to upgrade from the previous version.
As such, the latest Couchbase Columnar SDKs are tested against the latest versions.
Where older versions of the {name-sdk} pre-date significant new features in Columnar, those differences will be noted in this section.
////



// add when 2.2 EA Server released
////
=== API Version

include::{sdk_api}@analytics-sdk:shared:partial$compatibility.adoc[tag=api-version]
////



== SDK API Stability


=== Interface Stability

include::{version-common}@analytics-sdk:shared:partial$interface-stability-pars.adoc[tag=interface-stability-section]





////
=== Older Analytics SDK Versions

include::{version-common}@analytics-sdk:shared:partial$archive.adoc[tag=link]
////

////
Note the https://www.couchbase.com/support-policy[End of Life dates^] for {name-sdk} versions.
See the notes there for Support details.
////
