= {name-sdk} Quickstart Guide
:page-toclevels: 2
:description: Install, connect, try. A quick start guide to get you up and running with Enterprise Analytics and the {name-sdk}.

[abstract]
{description}




include::analytics-sdk:shared:partial$start-using-sdk.adoc[tag=intro]


== Before You Start

Install and configure an xref:enterprise-analytics:intro:intro.adoc[Enterprise Analytics Cluster].

////
Sign up for a xref:cloud:get-started:create-account.adoc[Capella account],
and choose a xref:columnar:intro:intro.adoc[Columnar] cluster.

You'll need to add your IP address to the allowlist, during the sign-up and cluster creation process (this can also be done at any time, via the UI, should the address change, or if you need to add a new one).
////


=== Prerequisites

Currently Python 3.9 - Python 3.12 is supported.
See the xref:project-docs:compatibility.adoc#platform-compatibility[compatibility page] for more information about platform support.


== Getting the SDK

The SDK can be installed via `pip`:

[source,console]
----
python -m pip install couchbase-analytics
----

For other installation methods, see the xref:project-docs:sdk-full-installation.adoc[installation page].



[quickstart]
== Connecting and Executing a Query


=== Synchronous API

[source,python]
----
include::devguide:example$python/overview.py
----

=== Asynchronous (asyncio) API

[source,python]
----
include::devguide:example$python/async_overview.py
----



=== Connection String

The `connStr` in the above example should takes the form of "https://<your_hostname>:" + PORT.
include::{version-common}@analytics-sdk:shared:partial$connstr.adoc[tag=connstr]




== Migration from Row-Based Analytics

include::{version-common}@analytics-sdk:shared:partial$migration.adoc[tag=migration]
